"use client";

import { ThemeProvider, CssBaseline } from "@mui/material";
import { theme } from "./theme"; // az előbb írt theme fájl
import Header from "@/components/Header";
import { CartProvider } from "@/context/CartContext";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="hu">
      <body>
        <Header /> {/* Fejléc hozzáadása */}
        <CartProvider>
          {" "}
          {/* Kosár kontextus hozzáadása */}
          <ThemeProvider theme={theme}>
            <CssBaseline /> {/* Alapértelmezett böngészőstílusok nullázása */}
            {children}
          </ThemeProvider>
        </CartProvider>
      </body>
    </html>
  );
}

/*
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
*/
